name: "RTXI"
tagline: "The Real-time eXperiment Interface"
description: "RTXI is a fast, open-source system for hard real-time, closed-loop data acquisition and stimulation for electrophysiology experiments."
rtxi_version: 2.0

url: "http://rtxi.org"
author :
   name : Ansel George
   email : info@rtxi.org
   github : rtxi

markdown: kramdown #rdiscount
highlighter: pygments
permalink: pretty #/:categories/:title

img: "/assets/img"
square_icon: "rtxi-logo-square.png"

pis: 
 - name: Robert Butera
   face: robert_butera.jpg
   where: Georgia Insititute of Technology
   url: https://neurolab.gatech.edu/labs/butera
 - name: David Christini
   face: david_christini.jpg
   where: Weill Cornell Medical College
   url: http://christinilab.org
 - name: Chuck Dorval
   face: chuck_dorval.jpg
   where: The University of Utah
   url: https://www.bioen.utah.edu/directory/profile.php?userID=593
 - name: John White
   face: john_white.jpg
   where: Boston University
   url: https://sites.google.com/site/johnwhitelab/

developers:
 - name: Ansel George
   face: ansel_george.jpg
   where: Weill Cornell Medical College
   url: https://github.com/anselg
 - name: Francis Ortega 
   face: francis_ortega.jpg
   where: Weill Cornell Medical College
   url: https://github.com/francis-ortega
 - name: Yogi Patel
   face: yogi_patel.jpg
   where: Georgia Insititute of Technology
   url: https://github.com/yapatel


gems:
 - jekyll-sitemap
 - jekyll-redirect-from
  

defaults:
   values:
      layout: "default"

exclude: 
 - "Gemfile"
 - "Gemfile.lock"
 - "LICENSE"
 - "relic" 
 - "assets/less/"
 - "Gruntfile.js"
 - "package.json"
 - "node_modules"
 - "bower.json"
 - "bower_components"
 - ".gitignore"

include: 
 - '.nojekyll'

sharing:
   provider: false
