name: "RTXI"
tagline: "The Real-time eXperiment Interface"
description: "RTXI is a fast, open-source system for hard real-time, closed-loop data acquisition and stimulation for electrophysiology experiments."

url: "http://rtxi.org"
author :
   name : Ansel George
   email : info@rtxi.org
   github : anselg

markdown: kramdown #rdiscount
highlighter: pygments
permalink: pretty #/:categories/:title

gems:
   - jekyll-sitemap

defaults:
   values:
      layout: "default"

exclude: [ "README.md", "Rakefile", "Gemfile", "Gemfile.lock", "LICENSE", "relic" ]

sharing:
   provider: false
