name: "RTXI"
tagline: "The Real-time eXperiment Interface"
description: ""

url: "/"
author :
   name : Ansel George
   email : info@rtxi.org
   github : anselg

markdown: rdiscount
highlighter: pygments
permalink: pretty

gems:
   - jekyll-sitemap

defaults:
   values:
      layout: "default"

collections:
   modules:
      output: true

exclude: [ "README.md", "Rakefile", "Gemfile", "Gemfile.lock", "LICENSE" ]

sharing:
   provider: false
