name: "RTXI"
taglind: "The Real-time eXperiment Interface"
description: ""

url: "/"
author :
   name : Ansel George
   email : info@rtxi.org
   github : anselg

markdown: kramdown #rdiscount
highlighter: pygments
permalink: pretty

gems:
   - jekyll-sitemap

exclude: [ "README.md", "Rakefile", "Gemfile", "Gemfile.lock", "LICENSE" ]

sharing:
   provider: false
